soil profile (Aida's work) and evaluation metrics
CSHS-CWRA/RavenPy pull request #199
Opened 2022-09-16 02:48 UTC by Bijan55699

Addition of two new soil profiles (Aida's work) and activation of evaluation period command.

2022-09-16 02:50 UTC, Bijan55699 commented
soil profile (Aida's work) and evaluation metrics

2022-09-16 13:10 UTC, huard requested changes

2022-09-16 13:10 UTC, huard commented on ravenpy/config/rvs.py
> +    :EvaluationPeriod      {evaluation_periods}
Unless there is a problem with the original formulation, this should not be changed. 

This is the definition of the EvaluationPeriod command:
 ```
@dataclass
class EvaluationPeriod(RavenCommand):
    """:EvaluationPeriod [period_name] [start yyyy-mm-dd] [end yyyy-mm-dd]"""

    name: str
    start: dt.date
    end: dt.date

    template = ":EvaluationPeriod {name} {start} {end}"

    def to_rv(self):
        return self.template.format(**asdict(self))
```
In practice, use something like (untested):
```
model.config.rvt.evaluation_periods = [EvaluationPeriod('wet', dt,date(1990, 1, 1), dt.date(2000, 1, 1))]
```

2022-09-16 13:11 UTC, huard commented
@Zeitsperre Seems to be a problem with the netcdf build. No objection pulling 3.7 from the suite if that simplifies things.

2022-09-16 14:28 UTC, Zeitsperre commented
I believe it's this issue here: https://github.com/Unidata/netcdf4-python/issues/1179. The wheel is bad on PyPI. I can add the fix for it in here at some point.

2022-09-19 14:17 UTC, Zeitsperre commented
@huard Python3.7 is rapidly approaching [end of life](https://peps.python.org/pep-0537/), so let's do that and see if the issue stems from there. I'm going to drop it in another PR.

2022-09-20 14:41 UTC, huard commented on ravenpy/config/rvs.py
> +    :EvaluationPeriod      {evaluation_periods}
What do you mean by "original formulation" ? 
https://github.com/CSHS-CWRA/RavenPy/blob/427f7caf0562928db1951e42b1217727bf925c62/ravenpy/config/commands.py#L80

If there's a but with the EvaluationPeriod configuration, let's fix it in another PR.

2022-10-26 19:04 UTC, closed without merging